// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixfktleikfbzcjmfkwth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4Zmt0bGVpa2ZiemNqbWZrd3RoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5ODc3MzMsImV4cCI6MjA2MjU2MzczM30.rfZVyEwrFaKi2xQJw4smMzu9knnvBSIpjcEhECbbsVU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);